
javascripts:
  - 'lib/jquery.js'
  - 'lib/jquery-ui.js'
  - 'lib/jquery-embedly.js'
  - 'lib/underscore.js'
  - 'lib/backbone.js'
  - 'lib/backbone-localstorage.js'
  - 'lib/less.js'
  - 'lib/strophe.js'
  - 'lib/timeago.js'
  - 'lib/md5.js'
  - 'app/controllers/*.coffee'
  - 'app/views/**/*.coffee'
  - 'app/models/post.coffee'
  - 'app/models/user.coffee'
  - 'app/models/*.coffee'
  - 'app/connectors/*.coffee'

stylesheets:
  - 'public/stylesheets/application.less'
  
specs:
  - 'lib/coffeescript.js'
  - 'spec/*/*.coffee'
  - 'spec/views/*/*.coffee'

fixtures:
  - 'spec/fixtures/*/*.xml'

templates:
  - 'app/templates/**/*.eco'
  