dependencies:
  - ConsoleDummy.js
  - es5-shim.js
  - document-redraw.js
  - underscore.js
  - jquery.npm-hack.js
  - jquery.js
  - jquery.copycss.js
  - jquery.textsaver.js
  - jquery.mousewheel.js
  - jquery.antiscroll.js
  - jquery.inputevent.js
  - jquery.autoresize.js
  - jquery.autoresize+input.js
  - jquery.autosuggestion.js
  - transform.js
  - backbone-master.js
  - backbone-localstorage.js
  - backbone-extensions.js
  - base64.js
  - strophe.js
  - strophe.disco.js
  - strophe.roster.js
  - strophe.pubsub.js
  - strophe.presence.js
  - strophe.register.js
  - strophe.dataforms.js
  - strophe.buddycloud.js
  - formatdate.js
  - modernizr.js
