dependencies:
  - ConsoleDummy.js
  - document-redraw.js
  - underscore.js
  - jquery.npm-hack.js
  - jquery.js
  - backbone-master.js
  - backbone-localstorage.js
  - backbone-extensions.js
  - base64.js
  - strophe.js
  - strophe.disco.js
  - strophe.roster.js
  - strophe.pubsub.js
  - strophe.register.js
  - strophe.dataforms.js
  - strophe.buddycloud.js
  - modernizr.js
